### ISSUE TITLE
Can't install due to corrupt version

### ISSUE THREAD

**Issue by TseWue** [YuLab-SMU/ggtreeExtra#1]
Hello there

Thank you so much for developing ggtreeExtra, it is exactly what I have been looking for! I was just going to use it but unfortunately I cannot install the package.

Here's the error message:

> devtools::install_github("xiangpin/ggtreeExtra")
Downloading GitHub repo xiangpin/ggtreeExtra@master
Error: Failed to install 'ggtreeExtra' from GitHub:
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/pkgbuild/R/pkgbuild.rdb' is corrupt
In addition: Warning messages:
1: In get0(oNam, envir = ns) : restarting interrupted promise evaluation
2: In get0(oNam, envir = ns) : internal error -3 in R_decompress1

info on my sesssion:

> version                  
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          6.0                         
year           2019                        
month          04                          
day            26                          
svn rev        76424                       
language       R                           
version.string R version 3.6.0 (2019-04-26)
nickname       Planting of a Tree

The error message says that pkgbuild.rdb is corrupt, are you guys working on it rn or do you know what is happening there?
Thank you so much for looking into this.

Best wishes,
Tse

**Comment by xiangpin** [comment]
It might be the issue of network. Since your platform is mac, you can use `git clone https://github.com/YuLab-SMU/ggtreeExtra.git` to clone it on terminal. then `cd ggtreeExtra`, and then `make build1 && make install` to install it. And you can view the vignettes using `browseVignettes("ggtreeExtra")`. Or you can use `remotes::install_github(YuLab-SMU/ggtreeExtra)`, again.

**Comment by TseWue** [comment]
Hi, thanks for the tips. I tried to install via terminal and there I got a different error message saying I need to upgrade R version to > 4.0. So I did that and it works! Thank you!
