### ISSUE TITLE
Error downloading - 'ggtreeExtra’ is not available (for R version 3.6.3)'

### ISSUE THREAD

**Issue by basilisk1233** [YuLab-SMU/ggtreeExtra#10]
Hello

I apologize for any naive questions, I'm rather new to using R. But I'm having issues downloading ggtreeExtra. 

When I try to install, I get this error:

> BiocManager::install("ggtreeExtra")
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.10 (BiocManager 1.30.16), R 3.6.3 (2020-02-29)
Installing package(s) 'ggtreeExtra'
Old packages: 'colorspace', 'data.table', 'quantreg'
Update all/some/none? [a/s/n]: 
n
Warning message:
In .inet_warning(msg) :
  package ‘ggtreeExtra’ is not available (for R version 3.6.3)
> if (!requireNamespace("BiocManager", quietly=TRUE))
+     install.packages("BiocManager")
> BiocManager::install("ggtreeExtra")
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.10 (BiocManager 1.30.16), R 3.6.3 (2020-02-29)
Installing package(s) 'ggtreeExtra'
Old packages: 'colorspace', 'data.table', 'quantreg'
Update all/some/none? [a/s/n]: 
a

  There are binary versions available but the source versions are later:
           binary source needs_compilation
colorspace  2.0-1  2.0-2              TRUE
data.table 1.13.6 1.14.0              TRUE
quantreg     5.85   5.86              TRUE

Do you want to install from sources the packages which need compilation? (Yes/no/cancel) no
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/colorspace_2.0-1.tgz'
Content type 'application/x-gzip' length 2558416 bytes (2.4 MB)
==================================================
downloaded 2.4 MB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/data.table_1.13.6.tgz'
Content type 'application/x-gzip' length 2398147 bytes (2.3 MB)
==================================================
downloaded 2.3 MB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/quantreg_5.85.tgz'
Content type 'application/x-gzip' length 1636906 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

The downloaded binary packages are in
	/var/folders/2m/htnr5shs15df4bmbtgy9987h0000gn/T//RtmpATLX47/downloaded_packages
Warning message:
In .inet_warning(msg) :
  package ‘ggtreeExtra’ is not available (for R version 3.6.3)

Any idea on how this could be fixed? Any help would be appreciated.

Best wishes

**Comment by xiangpin** [comment]
The R >= 4.1 is required by the ggtreeExtra. Your R platform should be updated.

**Comment by basilisk1233** [comment]
Ah, I was naively just updating RStudio but not the underlying R itself. Thanks for the suggestion, I've got ggtreeExtra installed now.
