### ISSUE TITLE
geom_fruit with geom = geom_tile can not adjust pwidth when x only have one unique value

### ISSUE THREAD

**Issue by PandengWang** [YuLab-SMU/ggtreeExtra#12]
Thanks so much for providing this useful tool!

When I want to add a geom_tile to the tree, the pwidth parameter doesn't work, if all the tiles on the same circle (x only has one unique value, as the following table show).

Do you have any idea about this issue?

Best regards,
Pandeng Wang

example data:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/wangp/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/wangp/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

OTUID| Phylum | Position
-- | -- | --
Zotu5 | p:Cyanobacteria | 1
Zotu9 | p:Proteobacteria | 1
Zotu4 | p:Proteobacteria | 1
Zotu1 | p:Cyanobacteria | 1
Zotu2 | p:Cyanobacteria | 1
Zotu7 | p:Cyanobacteria | 1
Zotu3 | p:Cyanobacteria | 1
Zotu8 | p:Proteobacteria | 1
Zotu10 | p:Actinobacteria | 1
Zotu14 | p:Proteobacteria | 1
Zotu15 | p:Cyanobacteria | 1

</body>

</html>

**Comment by xiangpin** [comment]
? Please refer to the [answer](https://github.com/YuLab-SMU/ggtreeExtra/issues/11#issuecomment-873335702)

**Comment by PandengWang** [comment]
> ? Please refer to the [answer](https://github.com/YuLab-SMU/ggtreeExtra/issues/11#issuecomment-873335702)

Thanks!
I found this answer. So I closed this issue.
