### ISSUE TITLE
Error: C stack usage  is too close to the limit

### ISSUE THREAD

**Issue by padingdun833** [YuLab-SMU/ggtreeExtra#13]
Hi dear developer,

I read your "ggtreeExtra的开发及其在宏基因组上的应用" from YuLabSMU wechat channel. It is a very nice and helpful tutorial.

But I meet the question like this:
![image](https://user-images.githubusercontent.com/86155600/132982716-dca6bca7-90b7-4e30-82cb-28f3bc6c9059.png)
I seek the answers for this in the Internet but all for linux systerm.would you have any answers for Windows platform?Thanks!

**Comment by xiangpin** [comment]
Please check the version of `tidytree`, `treeio`, `ggtree` and `ggtreeExtra`.
<img width="816" alt="xx" src="https://user-images.githubusercontent.com/17870644/132983704-548e1103-1c61-4f86-ad5d-e9f8cc5b47ea.png">

Then you can refer to the vignettes, https://bioconductor.org/packages/devel/bioc/vignettes/MicrobiotaProcess/inst/doc/Introduction.html#biomarker-discovery

**Comment by padingdun833** [comment]
> Please check the version of `tidytree`, `treeio`, `ggtree` and `ggtreeExtra`.
> <img alt="xx" width="816" src="https://user-images.githubusercontent.com/17870644/132983704-548e1103-1c61-4f86-ad5d-e9f8cc5b47ea.png">
> 
> Then you can refer to the vignettes, https://bioconductor.org/packages/devel/bioc/vignettes/MicrobiotaProcess/inst/doc/Introduction.html#biomarker-discovery

Thanks!It can works!
