### ISSUE TITLE
the open gap of the circle

### ISSUE THREAD

**Issue by padingdun833** [YuLab-SMU/ggtreeExtra#14]
![image](https://user-images.githubusercontent.com/86155600/132989333-67a3f1d5-ac47-4609-9006-42b9e0ebaa58.png)
data(mouse.time.mpse)
mouse.time.mpse %<>% 
  # 稀释抽平功能，有研究评估抽平对于微生物组数据有较好的鲁棒性
  mp_rrarefy(.abundance=Abundance) %>% 
  # 默认计算每个样品中所有层级的物种相对丰度（relative=TRUE）
  mp_cal_abundance(.abundance=RareAbundance) %>%
  # 计算time分组下的每个组别的所有层级的物种相对丰度 
  mp_cal_abundance(.abundance=RareAbundance, .group=time)
mouse.time.mpse
trda <- mouse.time.mpse %>%
  mp_diff_analysis(.abundance=RelRareAbundanceBySample, 
                   .group=time, 
                   first.test.alpha=0.05,
                   action="add")
trda <- trda %>% mp_extract_tree(type="taxatree")

# detach(package:tidytree)
# remotes::install_github("YuLab-SMU/tidytree")#开发版
# library(tidytree)
trda %>% unnest(RareAbundanceBySample)
trda
trda %>% unnest(RareAbundanceBytime)
# p1 绘制内部的环形进化树图
# td_filter 可以对plot data进行操作 (td_filter(nodeClass == "Phylum")(p1$data))
p1 <- ggtree(
  trda, 
  layout="radial",
  size = 0.3
) +
  geom_point(
    data = td_filter(!isTip),
    fill="white", 
    size=1, 
    shape=21
  )
# p2 绘制中间门水平的高亮图层
p2 <- p1 +
  geom_hilight(
    data = td_filter(nodeClass == "Phylum"),
    mapping = aes(node = node, fill = label)
  )

# p3 绘制外圈的点图，用来展示不同OTU在每个样本中的丰度信息
# td_unnest 与 td_filter类似 
p3 <- p2 +
  ggnewscale::new_scale("fill") +
  geom_fruit(
    data = td_unnest(RareAbundanceBySample),
    geom = geom_star,
    mapping = aes(
      x = fct_reorder(Sample, time, .fun=min),
      size = RelRareAbundanceBySample,
      fill = time,
      subset = RelRareAbundanceBySample > 0
    ),
    starshape = 13,
    starstroke = 0.25,
    offset = 0.04,
    pwidth = 0.8,
    grid.params = list(linetype=2)
  ) +
  scale_size_continuous(
    name="Relative Abundance (%)",
    range = c(1, 3)
  ) +
  scale_fill_manual(values=c("#1B9E77", "#D95F02"))

# p4 绘制tip节点的名称，为了更好地观察，将其标注在点图外
p4 <- p3 + geom_tiplab(size=2, offset=7.2)

# p5 绘制组间有差异的OTU的线性判别效应值(log10(LDA))
p5 <- p4 +
  ggnewscale::new_scale("fill") +
  geom_fruit(
    geom = geom_col,
    mapping = aes(
      x = LDAmean,
      fill = Sign_time,
      subset = !is.na(LDAmean)
    ),
    orientation = "y",
    offset = 0.3,
    pwidth = 0.5,
    axis.params = list(axis = "x", 
                       title = "Log10(LDA)", 
                       title.height = 0.1, 
                       title.size = 2, 
                       text.size = 1.8, 
                       vjust = 1,
                       nbreak=4),
    grid.params = list(linetype = 2)
  )

# p6 绘制所有分类水平中组间经过kruskal.test(默认)检验并进行FDR校正的FDR值
p6 <- p5 + 
  ggnewscale::new_scale("size") +
  geom_point(
    data=td_filter(!is.na(fdr)),
    mapping = aes(size = -log10(fdr),
                  fill = Sign_time,
    ),
    shape = 21,
  ) +
  scale_size_continuous(range=c(1, 3)) + 
  scale_fill_manual(values=c("#1B9E77", "#D95F02"))  

p6 + theme(
  legend.key.height = unit(0.3, "cm"),
  legend.key.width = unit(0.3, "cm"),
  legend.spacing.y = unit(0.02, "cm"),
  legend.text = element_text(size = 7), 
  legend.title = element_text(size = 9),
)
# the question is :
1.the picture above is different from the example picture
2.the mapping angle of the second half circle does not match
3.the open gap is too big
#Example picture:
![微信图片_20210912213307](https://user-images.githubusercontent.com/86155600/132989642-28d5c391-ec68-406b-b0a2-0ef45118ccd4.jpg)
Thanks!

**Comment by xiangpin** [comment]
+ 1. This is because the `first.test.alpha` was set to `0.01` in the `vignettes`, but it was set to `0.05` in the example of wechat.

+ 2. The `title.height` should be reduced (in `p5`), it was set to `0.01` in the example and vignettes, but, it is `0.1` in your codes.

**Comment by padingdun833** [comment]
oh,thanks!
