### ISSUE TITLE
combine ggtreeExtra with ggmsa

### ISSUE THREAD

**Issue by DanielRivasMD** [YuLab-SMU/ggtreeExtra#16]
Hi, I like this package. I would like to combine `geom_fruit` with `geom_msa` as indicated in the documentation (with `rectangular` shape). However, I have not managed to align the `ID` properly to plot the adequate MSA to tree tip. Any help would be appreciated. Cheers

**Comment by xiangpin** [comment]
please refer to the [request](https://github.com/YuLab-SMU/ggmsa/pull/16).

**Comment by DanielRivasMD** [comment]
Awesome! Appreciated
