### ISSUE TITLE
log scale and ggbreak

### ISSUE THREAD

**Issue by padingdun833** [YuLab-SMU/ggtreeExtra#18]
Hello!
In order to effectively utilize plotting space using ggtreeExtra,I using ggbreak to split the axis.But there is a problem.Here's the details.
Codes:
ggtree(physeq, size = 0.3,layout = "circular",branch.length = "none") +
  geom_tippoint(
    mapping=aes(color = phylum),
    show.legend = T,
    size=1.5
  )+
  geom_tiplab(offset = 0.25,size=1,align = T,linetype = "solid")+
  scale_color_manual(values = palette) +
  geom_fruit(
    data = melt_simple_1,
    geom = geom_density_ridges,
    mapping = aes(
      y = OTU,
      x = val,
      fill =phylum
    ),
    offset = 0.12,
    pwidth = 0.4,
    lwd = .05,
    axis.params = list(
      axis = "x",
      text.size = 1,
      hjust = 0.5,
      vjust = 1
    ),
    grid.params = list(),
    show.legend = FALSE
  )+
  scale_fill_manual(values = palette)+
  scale_x_break(breaks = c(3000,5000))
Error:
![image](https://user-images.githubusercontent.com/86155600/144954974-0fb16781-c25f-45d3-a8c6-25a99e1ee3d7.png)
Then,I tried to solve the problem using log scale.Here are the datails：
ggtree(physeq, size = 0.3,layout = "circular",branch.length = "none") +
  geom_tippoint(
    mapping=aes(color = phylum),
    show.legend = T,
    size=1.5
  )+
  geom_tiplab(offset = 0.25,size=1,align = T,linetype = "solid")+
  scale_color_manual(values = palette) +
  geom_fruit(
    data = melt_simple_1,
    geom = geom_density_ridges,
    mapping = aes(
      y = OTU,
      **x = round(log2(val),4)**,
      fill =phylum
    ),
    offset = 0.12,
    pwidth = 0.4,
    lwd = .05,
    axis.params = list(
      axis = "x",
      text.size = 1,
      hjust = 0.5,
      vjust = 1
    ),
    grid.params = list(),
    show.legend = FALSE
  )+
  scale_fill_manual(values = palette)
Error:
![image](https://user-images.githubusercontent.com/86155600/144955343-1cc96487-cb82-4076-9eaf-c7cfda8a6057.png)
![image](https://user-images.githubusercontent.com/86155600/144955379-a4aae3ff-60f6-4119-926a-abb75727048e.png)
Thanks!

**Comment by padingdun833** [comment]
This is the figure after the data is deleted.But it's still not ideal, the graphics are too crowded
![image](https://user-images.githubusercontent.com/86155600/144956831-c63acbfa-a3b3-4a9e-9ed2-4fa3f839d14b.png)

**Comment by xiangpin** [comment]
1. The `ggbreak` is not compatible with the circular layout of ggtree.
2. How about setting `x` of mapping to `aes(x=log(val+1))`.
3. Or you can use `geom_star` layer to display the abundance of each taxon for each sample, you can refer to the [answer](https://github.com/YuLab-SMU/MicrobiotaProcess/issues/35#issuecomment-979686735).
