### ISSUE TITLE
Chapter 10.3 ggtreeExtra: geom_hilight

### ISSUE THREAD

**Issue by Tsingsjeen** [YuLab-SMU/ggtreeExtra#5]
I run the code:

p <- ggtree(tree, layout="fan", size=0.15, open.angle=5) +
  geom_hilight(data=nodedf, mapping=aes(node=node),
               extendto=6.8, alpha=0.3, fill="grey", color="grey50",
               size=0.05)

And there is an error:

Error in structure(list(node = node, fill = fill, alpha = alpha, extend = extend,  : 
  argument "node" is missing, with no default

Do you know what is the problem? thanks!

**Comment by xiangpin** [comment]
Please update ggtree to the latest [version](https://github.com/YuLab-SMU/ggtree/blob/master/NEWS.md).
